#!/bin/bash

ssh_config_path="$HOME/.ssh/config_gwitch"
temp_ssh_config_path="$HOME/.ssh/config_temporary"

new_primary_username=`echo "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
curr_primary_username=`awk '/^Host github\.com$/,/#Username/{print $2}' $ssh_config_path | tail -1`

if ! [[ $new_primary_username = *[!\ ]* ]]; then
  echo "You did not enter a username"
  exit 1;
fi

host_new_username_count=`grep -o "#Username $new_primary_username" $ssh_config_path | wc -l`
githubdotcom_username_count=`grep -o "Host github.com" $ssh_config_path | wc -l`
if ! [ $host_new_username_count = "1" -a $githubdotcom_username_count = "1" ]; then
	echo "Couldn't find a suitable entry for $new_primary_username in ssh config file"
	exit 1;
fi

if [ "$new_primary_username" == "$curr_primary_username" ]; then 
	echo "This is already the current username";
	exit 1;
fi

new_user_name=`awk "/^Host github-$new_primary_username$/,/#Name/{print $2}" $ssh_config_path | tail -1 | sed 's/#Name //' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
new_user_email=`awk "/^Host github-$new_primary_username$/,/#Email/{print $2}" $ssh_config_path | tail -1 | sed 's/#Email //' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`

echo "Switching from $curr_primary_username to $new_primary_username"
echo "Setting name to $new_user_name"
echo "Setting email to $new_user_email"

awk -v new_primary_username_regex="Host github-$new_primary_username" -v curr_primary_username="$curr_primary_username" '
 !y{y=sub(/Host github\.com/,"Host github-"curr_primary_username)}
 !x{x=sub(new_primary_username_regex,"Host github.com")}
 1' "$ssh_config_path" > "$temp_ssh_config_path" && mv "$temp_ssh_config_path $ssh_config_path"


git config --global user.email "$new_user_email"
git config --global user.name "$new_user_name"
